Day2/Models/Instructor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Day2.Models
{
    public class Instructor
    {
        public int Id { set; get; }
        public string Name { set; get; }
        [Required(ErrorMessage = "Please choose file to upload.")]
        public string Image { set; get; }
        public string address { set; get; }
        public double salary { set; get; }
        [ForeignKey("department")]
        public int departmentId { set; get; }
        [ForeignKey("course")]
        public int courseId { set; get; }
        public virtual Course course { set; get; }
        public virtual Department department { set; get; }
    }
}

Day2/Controllers/InstructorController.cs
using Day2.Models;
using Day2.ViewModel;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;

namespace Day2.Controllers
{
    public class InstructorController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        DB_Context db =new DB_Context();
        public InstructorController(IWebHostEnvironment environment)
    {
        _environment = environment;
    }
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            List<Instructor> instructors = db.instructors.ToList();
            return View(instructors);
        }
        public IActionResult Details(int id)
        {
            
            Instructor insModel = db.instructors.FirstOrDefault(x => x.Id == id);
            Instructor_Course_DepartmentViewModel insVM =  new Instructor_Course_DepartmentViewModel();
            insVM.instructor_id = insModel.Id;
            insVM.instructor_name = insModel.Name;
            insVM.instructor_image = insModel.Image;
            insVM.instructor_Address = insModel.address;
            insVM.course = insModel.course;
            insVM.dep = insModel.department;

            return View(insVM);
        }

        public IActionResult GetCourseByDept(int deptId)
        {
            List<Instructor_Course_DepartmentViewModel> course = db.courses.Where(c => c.departmentId == deptId)
                                                                                                                                                     .Select(c => new Instructor_Course_DepartmentViewModel {
                course_id = c.Id,
                course_name = c.Name
            })
        .ToList();
          return Json(course);
        }
        public IActionResult New()
        {

            ViewData["Clist"] = db.courses.ToList();
            ViewData["Dlist"] = db.departments.ToList();
            View();
            return View();
        }
        
        [HttpPost]
        public async Task<ActionResult> Save(Instructor instructor, IFormFile Image)
        {
            if (instructor.Name != null && instructor.salary>6000 && Image != null)
            {
                string filename = Image.FileName;
                filename = Path.GetFileName(filename);

                string uploadFilePath = Path.Combine(_environment.WebRootPath, "images", filename);

                await using var stream = new FileStream(uploadFilePath, FileMode.Create);
                await Image.CopyToAsync(stream);
                db.instructors.Add(new Instructor()
                {
                    Name=instructor.Name,
                    salary=instructor.salary,
                    address=instructor.address,
                    courseId=instructor.courseId,
                    departmentId=instructor.departmentId,
                    Image= filename
                });
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["Clist"] = db.courses.ToList();
            ViewData["Dlist"] = db.departments.ToList();
            return View("New", instructor);
            
        }

        public IActionResult Edit(int id)
        {
            Instructor InsModel = db.instructors.FirstOrDefault(i => i.Id == id);
            ViewData["DList"] = db.departments.ToList();
            ViewData["CList"] = db.courses.ToList();

            return View(InsModel);
            
        }
        [HttpPost]
        public async Task<ActionResult> Edit(Instructor ins, int id, IFormFile Image)
        {

            if (ins.Name != null && ins.salary > 6000 )
            {
                Instructor InsModel = db.instructors.FirstOrDefault(i => i.Id == id);
                InsModel.Name    = ins.Name;
                InsModel.address = ins.address;
                InsModel.departmentId = ins.departmentId;
                InsModel.courseId = ins.courseId;
                InsModel.salary      = ins.salary;
                if (Image != null)
                {
                    string filename = Image.FileName;
                    filename = Path.GetFileName(filename);
                    string uploadFilePath = Path.Combine(_environment.WebRootPath, "images", filename);
                    await using var stream = new FileStream(uploadFilePath, FileMode.Create);
                    await Image.CopyToAsync(stream);
                    InsModel.Image = filename;
                }

                db.SaveChanges();
              return  RedirectToAction("Index");
            }

            ViewData["DList"] = db.departments.ToList();
            ViewData["CList"] = db.courses.ToList();
            return View(ins);

        }
        public IActionResult Search(string search)
        {
            var ins = db.instructors.Where(i=>i.Name== search).ToList();
            ViewData["search"] = search;
            return View("index",ins);
        }
    }
}

Day2/Views/Instructor/Details.cshtml
@model Day2.ViewModel.Instructor_Course_DepartmentViewModel;
@{
    ViewData["Title"] = "Details";
    Layout = "_ProfileLayout";
}

<div class="col-lg-5">
    <img class="img-fluid rounded mb-4 mb-lg-0" src="/Images/@Model.instructor_image" alt="">
</div>
<div class="col-lg-7">
    <div class="text-left mb-4">
        <h1>@Model.instructor_name</h1>
        <h5 class="text-primary text-uppercase mb-3" style="letter-spacing: 5px;"> @Model.instructor_Address</h5>
        
    </div>
    <p>
        <ul>
            <li>Course : @Model.course.Name</li>
            <li>department Name : @Model.dep.Name</li>
        </ul>
    </p>
    <a href="/instructor/index" class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold mt-2">Home</a>
</div>

  

Day2/Views/Instructor/Edit.cshtml
@model Instructor
@{
    Layout = "_FormLayout";
    ViewData["Title"] = "Edit";
}



<h2 class="text-primary text-uppercase mb-3 d-flex justify-content-center" style="letter-spacing: 5px;"><i class="fas fa-chalkboard-teacher"></i>Edit Instructor</h2>

<form method="post"  enctype="multipart/form-data">
    @* asp-action="New" asp-controller="Employee" asp-route-id="@Model.Id">*@
    <div class="form-group">
        <label>Instructor Name</label>
        <input type="text" name="Name" id="Name" value="@Model?.Name" class="form-control" />
    </div>
    <div class="form-group">
        <label>Course Name</label>
        <select name="courseId" id="courseId" class="form-control">
            @foreach (Course cItem in ViewBag.Clist)
            {
                if (cItem.Id == Model.courseId)
                {
                    <option value="@cItem.Id" selected>@cItem.Name</option>
                }
                else
                {
                    <option value="@cItem.Id">@cItem.Name</option>
                }
            }
        </select>
    </div>
    <div class="form-group">
        <label>Address </label>
        <input type="text" name="address" id="address" value="@Model?.address" class="form-control" />
    </div>
    <div class="form-group">
        <label>Salary </label>
        <input type="number" name="salary" id="salary" value="@Model?.salary" class="form-control" />
    </div>
    <div class="form-group">
        <label>Department </label>
        <select name="departmentId" id="departmentId" class="form-control">
            @foreach (Department dItem in ViewBag.Dlist)
            {
                if (dItem.Id == Model.departmentId)
                {
                    <option value="@dItem.Id" selected>@dItem.Name</option>
                }
                else
                {
                    <option value="@dItem.Id">@dItem.Name</option>
                }
            }
        </select>
    </div>
    <div class="form-group">
        <label for="imageUpload">Upload Image:</label>
        <input type="file" class="form-control" id="Image" name="Image" accept=".jpg,.png,image/*">
        <p class="form-text ps-5 text-decoration-underline" id="Path_Img">@Model.Image</p>

    </div>
    <div div class="form-group d-flex justify-content-center">
        <input type="submit" value="Update" class="btn btn-primary mt-4 " />
    </div>
    </form>
<br /><br />
<a asp-action="Index" class="d-flex justify-content-center">Back To List</a>

    <!-------------Js VAlidation Client side Library--------------->
@section Scripts{
    <script>
        document.getElementById('Image').addEventListener('change', handleFileSelect, false);

        function handleFileSelect(event) {
            var input = event.target;
            if (input.files && input.files[0]) {
                document.getElementById('Path_Img').innerHTML = input.files[0].name;
            }

        }
    </script>
}

Day2/Views/Instructor/Index.cshtml
@model List<Instructor>
@{
    Layout = "_InstructorLayout";
    ViewData["Title"] = "Index";
}

@section searchsection{
    <a href="/instructor/index" class=" btn btn-link d-flex justify-content-center font-weight-bolder">ALL</a>
<form action="/instructor/Search" method="post">
    <div class="d-flex justify-content-center p-4 m-2">
        <label class="form-label px-4 m-2 text-primary" value="@ViewBag?.search">Search</label>
        <input type="text" class="form-control w-50 px-2" name="search" />
        <button type="submit" class="btn">
            <a href="" class="pe-0">
            <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
            </svg>
        </a>
        </button>

    </div>
</form>
   

}

    @foreach (Instructor item in Model)
    {
        <div class="col-md-6 col-lg-3 text-center team mb-4">
            <div class="team-item rounded overflow-hidden mb-2">
            <div class="team-img position-relative">
                    <img class="img-fluid " src="/Images/@item.Image" alt="">
              
                    <div class="team-social">
                        <a class="btn btn-outline-light btn-square mx-1" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-square mx-1" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-square mx-1" href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-light btn-square mx-1" href="@Url.Action("details","Instructor",new{id=item.Id})"><i class="fas fa-info"></i></a>
                        <a class="btn btn-outline-light btn-square mx-1" href="@Url.Action("Edit","Instructor",new{id=item.Id})"><i class="fas fa-user-edit"></i></a>
                    </div>
                </div>
                <div class="bg-secondary p-4">
                    <h5>@item.Name</h5>
                    <p class="m-0">@item.address</p>
                </div>
            </div>
        </div>
        
    }
@section newsection{
    <a href="/instructor/New" class=" btn btn-link d-flex justify-content-center font-weight-bolder"><i class="fas fa-plus-circle mr-2"></i>Add New Instructor</a>
}

Day2/Views/Instructor/New.cshtml
@model Instructor
@{
    ViewData["Title"] = "New";
    Layout = "_FormLayout";

    SelectList depItems = new SelectList(ViewBag.DList, "Id", "Name");
}

<h1 class="text-center "><i class="fas fa-chalkboard-teacher"></i>Add New Instructor</h1>

<form method="post" class="form-group p-2" action="~/instructor/Save" enctype="multipart/form-data">

    <div class="form-group">
        <label>Instructor Name</label>
        <input type="text" name="Name" id="Name" value="@Model?.Name" class="form-control" />
    </div>
    <div class="form-group">
        <label>Address </label>
        <input type="text" name="address" id="address" value="@Model?.address" class="form-control" />
    </div>
    <div class="form-group">
        <label>Salary </label>
        <input type="number" name="salary" id="salary" value="@Model?.salary" class="form-control" />
    </div>
    <div class="control-group">
        <label asp-for="departmentId">Department</label>
        @* <input class="form-control" asp-for="DeptID" />*@
        <select class="form-control" id="deptID" asp-for="departmentId" asp-items="depItems" onchange=" changeDeptID()">
            <option value="0">--Select Department--</option>
        </select>
    </div>
    <div class="form-group">
        <label>Course Name</label>
        <select name="courseId" id="courseId" class="form-control">
        </select>
    </div>
    <div class="form-group ">
        <label for="imageUpload">Upload Image:</label><br />
        <input type="file" class="form-control " name="Image">
    </div>
    <iv class="form-group d-flex justify-content-center">
        <input type="submit" value="Create" class="btn btn-primary mt-4 " />

    </iv>
    </form>
@section Scripts{
    <script src="~/lib/jquery/dist/jquery.js"></script>

    <script>
        function changeDeptID(){
            var deptID = document.getElementById("deptID").value;
            console.log(deptID)
            $.ajax({
                url: "/instructor/GetCourseByDept?deptId=" + deptID,
                success: function (result) {
                    console.log(result);
                    document.getElementById("courseId").innerHTML="";
                    for(let i of result){
                        document.getElementById("courseId").innerHTML+=
                            "<option value=" + i.course_id + ">" + i.course_name + "</option>"
                    }
                }
            })
               }
        
        </script>
      
    }